apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-service-deployment
  labels:
    app: platform-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service
  template:
    metadata:
      labels:
        app: platform-service
    spec:
      containers:
      - name: platform-service
        image: cranberrywine/platform-service:latest
        ports:
        - containerPort: 8080
        # Todo: Add configMap for environment variables.
        env:
        - name: "CommandService"
          value: "http://command-service-cluster-ip-service:8080"
        - name: "ConnectionStrings__MSSQL"
          valueFrom:
            secretKeyRef:
              name: mssql-ext
              key: CONNECTION_STRING
---
apiVersion: v1
kind: Service
metadata:
  name: platform-service-node-port-service
spec:
  type: NodePort
  selector:
    app: platform-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: platform-service-cluster-ip-service
spec:
  selector:
    app: platform-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080